# Generated by Django 5.2.6 on 2026-01-21 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Código')),
                ('first_name', models.CharField(max_length=100, verbose_name='Primer Nombre')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Segundo Nombre')),
                ('last_name_paternal', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('last_name_maternal', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('curp', models.CharField(max_length=18, unique=True, verbose_name='CURP')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField(verbose_name='Fecha de Internamiento')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actualmente Participando')),
                ('study', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='studies.study')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='volunteers.volunteer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('volunteer',), name='unique_active_participation')],
            },
        ),
    ]
