# Generated by Django 5.2.6 on 2026-01-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='participation',
            name='unique_active_participation',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='admission_date',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='payment_date',
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='code',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='curp',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name_maternal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name_paternal',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='sex',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
    ]
