# Generated by Django 5.2.6 on 2026-01-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_remove_participation_unique_active_participation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='curp',
            field=models.CharField(error_messages={'unique': 'Ya existe un voluntario registrado con esta CURP.'}, max_length=18, unique=True, verbose_name='CURP'),
        ),
    ]
