# Generated by Django 5.2.6 on 2026-01-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_alter_volunteer_curp'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='manual_status',
            field=models.CharField(choices=[('waiting_approval', 'En espera por aprobación'), ('eligible', 'Apto'), ('rejected', 'Rechazado')], default='waiting_approval', max_length=20, verbose_name='Estatus Administrativo'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='status_reason',
            field=models.TextField(blank=True, verbose_name='Motivo del Estatus'),
        ),
    ]
