# Generated by Django 5.2.6 on 2026-01-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0004_volunteer_manual_status_volunteer_status_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
