# Generated by Django 5.2.6 on 2026-02-09 22:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_alter_study_is_active'),
        ('volunteers', '0005_volunteer_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='participation',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participation',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studies.study'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='curp',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z]{4}\\d{6}[HM][A-Z]{5}[0-9A-Z]\\d$', 'Formato CURP inválido')]),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='last_name_maternal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='manual_status',
            field=models.CharField(choices=[('waiting_approval', 'En espera por aprobación'), ('eligible', 'Apto'), ('rejected', 'Rechazado'), ('age_mismatch', 'No elegible por edad'), ('in_study', 'En estudio'), ('study_assigned', 'Estudio asignado'), ('standby', 'En espera (Descanso)')], default='waiting_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
