# Generated by Django 5.2.6 on 2026-02-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0006_participation_assigned_at_alter_participation_study_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='contacted',
            field=models.BooleanField(default=False, verbose_name='Contactado por WhatsApp'),
        ),
    ]
