# Generated by Django 5.2.6 on 2026-02-17 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0007_volunteer_contacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='contacted',
            field=models.BooleanField(default=False, verbose_name='Contactado'),
        ),
    ]
