# Generated by Django 5.2.6 on 2026-02-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0008_alter_volunteer_contacted'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='rejection_category',
            field=models.CharField(blank=True, choices=[('IMC', 'IMC'), ('Laboratoriales', 'Laboratoriales'), ('Incumplimiento', 'Incumplimiento'), ('Otro', 'Otro')], max_length=20, null=True, verbose_name='Categoría de Rechazo'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones / Motivo'),
        ),
    ]
