# Generated by Django 5.2.6 on 2026-02-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0009_volunteer_rejection_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='manual_status',
            field=models.CharField(choices=[('waiting_approval', 'En espera por aprobación'), ('eligible', 'Apto'), ('rejected', 'Rechazado'), ('age_mismatch', 'No elegible por edad'), ('in_study', 'En estudio'), ('study_assigned', 'Estudio asignado'), ('standby', 'En espera (Descanso)'), ('reevaluation', 'Reevaluación')], default='waiting_approval', max_length=20),
        ),
    ]
