# Generated by Django 5.2.6 on 2026-02-25 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0010_alter_volunteer_manual_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='contacted',
            field=models.CharField(choices=[('not_contacted', 'No contactado'), ('contacted_yes', 'Contactado (Sí)'), ('contacted_no_response', 'No respondió'), ('contacted_rejected', 'Rechazó')], default='not_contacted', max_length=30, verbose_name='Estatus de Contacto'),
        ),
    ]
