# Generated by Django 5.2.6 on 2026-02-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0010_alter_volunteer_manual_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='contacted',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='contact_status',
            field=models.CharField(choices=[('not_contacted', 'No Contactado'), ('pending', 'Pendiente de Respuesta'), ('confirmed', 'Confirmado (Sí)'), ('declined', 'Rechazado (No)')], default='not_contacted', max_length=20, verbose_name='Estatus de Contacto'),
        ),
    ]
