# Generated by Django 5.2.6 on 2026-02-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0011_remove_volunteer_contacted_volunteer_contact_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='contact_status',
        ),
        migrations.RemoveField(
            model_name='volunteer',
            name='rejection_category',
        ),
        migrations.AddField(
            model_name='volunteer',
            name='contacted',
            field=models.BooleanField(default=False, verbose_name='Contactado'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='manual_status',
            field=models.CharField(choices=[('waiting_approval', 'En espera por aprobación'), ('eligible', 'Apto'), ('rejected', 'Rechazado'), ('age_mismatch', 'No elegible por edad'), ('in_study', 'En estudio'), ('study_assigned', 'Estudio asignado'), ('standby', 'En espera (Descanso)')], default='waiting_approval', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='status_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
