# Generated by Django 5.2.6 on 2026-02-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0012_remove_volunteer_contact_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='contacted',
            field=models.CharField(choices=[('not_contacted', 'No contactado'), ('confirmed', 'Confirmado (Sí)'), ('pending', 'Pendiente de Respuesta'), ('declined', 'Rechazado (No)')], default='not_contacted', max_length=20, verbose_name='Estatus de Contacto'),
        ),
    ]
