# Generated by Django 5.2.6 on 2026-01-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='admission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Internamiento'),
        ),
        migrations.AddField(
            model_name='study',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='study',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Vigente'),
        ),
    ]
