# Generated by Django 5.2.6 on 2026-01-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0002_study_admission_date_study_payment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
