# Generated by Django 5.2.6 on 2026-02-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0003_alter_study_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='doses',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Dosis'),
        ),
        migrations.AddField(
            model_name='study',
            name='molecules',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Moléculas'),
        ),
        migrations.AddField(
            model_name='study',
            name='sponsor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Patrocinador'),
        ),
    ]
