# Generated by Django 5.2.6 on 2026-03-12 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0004_study_doses_study_molecules_study_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Código del Estudio'),
        ),
    ]
