# Generated by Django 5.2.6 on 2026-01-21 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Edición'), ('DELETE', 'Eliminación')], max_length=10)),
                ('model_affected', models.CharField(max_length=100)),
                ('record_id', models.CharField(max_length=100)),
                ('changes', models.JSONField(verbose_name='Cambios realizados')),
                ('justification', models.TextField(verbose_name='Justificación')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
